export type BackgroundTemplate = {
  id: string;
  category: string;
  label: string;
  url: string;
  themePreset: string;
  themeDetails: string; // The exact background description to inject
};

export const backgroundTemplates: BackgroundTemplate[] = [
  // Pastels & Solids
  {
    id: "bg_white",
    category: "Solids & Pastels",
    label: "Pure White Studio",
    url: "/background-templates/bg_solid_white_1775101602461.png",
    themePreset: "custom",
    themeDetails: "pure white blank studio background, soft diffused lighting, minimalist",
  },
  {
    id: "bg_black",
    category: "Solids & Pastels",
    label: "Deep Black Studio",
    url: "/background-templates/bg_solid_black_1775101619858.png",
    themePreset: "custom",
    themeDetails: "pure deep black blank studio background, cinematic subtle reflections",
  },
  {
    id: "bg_pastel_pink",
    category: "Solids & Pastels",
    label: "Pastel Pink",
    url: "/background-templates/bg_pastel_pink_1775101426375.png",
    themePreset: "custom",
    themeDetails: "pastel pink empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_blue",
    category: "Solids & Pastels",
    label: "Pastel Blue",
    url: "/background-templates/bg_pastel_blue_1775101443401.png",
    themePreset: "custom",
    themeDetails: "pastel blue empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_green",
    category: "Solids & Pastels",
    label: "Pastel Green",
    url: "/background-templates/bg_pastel_green_1775101459483.png",
    themePreset: "custom",
    themeDetails: "pastel green empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_yellow",
    category: "Solids & Pastels",
    label: "Pastel Yellow",
    url: "/background-templates/bg_pastel_yellow_1775101476464.png",
    themePreset: "custom",
    themeDetails: "pastel yellow empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_purple",
    category: "Solids & Pastels",
    label: "Pastel Purple",
    url: "/background-templates/bg_pastel_purple_1775101496328.png",
    themePreset: "custom",
    themeDetails: "pastel purple empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_peach",
    category: "Solids & Pastels",
    label: "Pastel Peach",
    url: "/background-templates/bg_pastel_peach_1775101512550.png",
    themePreset: "custom",
    themeDetails: "pastel peach empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_mint",
    category: "Solids & Pastels",
    label: "Pastel Mint",
    url: "/background-templates/bg_pastel_mint_1775101527878.png",
    themePreset: "custom",
    themeDetails: "pastel mint empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_lilac",
    category: "Solids & Pastels",
    label: "Pastel Lilac",
    url: "/background-templates/bg_pastel_lilac_1775101542393.png",
    themePreset: "custom",
    themeDetails: "pastel lilac empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_coral",
    category: "Solids & Pastels",
    label: "Pastel Coral",
    url: "/background-templates/bg_pastel_coral_1775101560643.png",
    themePreset: "custom",
    themeDetails: "pastel coral empty studio background, soft diffused lighting",
  },
  {
    id: "bg_pastel_aqua",
    category: "Solids & Pastels",
    label: "Pastel Aqua",
    url: "/background-templates/bg_pastel_aqua_1775101575934.png",
    themePreset: "custom",
    themeDetails: "pastel aqua empty studio background, soft diffused lighting",
  },

  // Environments
  {
    id: "bg_studio",
    category: "Environments",
    label: "Studio",
    url: "/background-templates/bg_env_studio_1775101634526.png",
    themePreset: "studio",
    themeDetails: "bright modern ecommerce studio set, seamless white backdrop, soft daylight",
  },
  {
    id: "bg_beach",
    category: "Environments",
    label: "Beach",
    url: "/background-templates/bg_env_beach_1775101654076.png",
    themePreset: "beach",
    themeDetails: "sunny coastal beach, clean sand, gentle waves, daytime, airy vacation vibe",
  },
  {
    id: "bg_sunset_shoreline",
    category: "Environments",
    label: "Sunset Shoreline",
    url: "/background-templates/bg_env_sunset_shoreline_1775101673010.png",
    themePreset: "sunset shoreline",
    themeDetails: "golden hour beach at sunset, warm sky gradient, soft water reflections",
  },
  {
    id: "bg_arcade",
    category: "Environments",
    label: "Arcade",
    url: "/background-templates/bg_env_arcade_1775101692250.png",
    themePreset: "arcade",
    themeDetails: "modern neon-lit arcade, colorful ambient lights, playful nightlife",
  },
  {
    id: "bg_city",
    category: "Environments",
    label: "City Street",
    url: "/background-templates/bg_env_city_1775101709183.png",
    themePreset: "upscale city street",
    themeDetails: "modern city street, elegant storefronts, clean sidewalks, daylight",
  },

  // Newly Generated Environments
  {
    id: "bg_rooftop",
    category: "Environments",
    label: "Rooftop",
    url: "/background-templates/bg_rooftop_new_1775221503091.png", 
    themePreset: "rooftop terrace",
    themeDetails: "modern rooftop with skyline, golden hour, premium lifestyle vibe",
  },
  {
    id: "bg_coffee_shop",
    category: "Environments",
    label: "Coffee Shop",
    url: "/background-templates/bg_coffee_shop_new_1775221520994.png",
    themePreset: "coffee shop",
    themeDetails: "modern cafe interior, warm daylight, trendy lifestyle vibe",
  },
  {
    id: "bg_garden",
    category: "Environments",
    label: "Garden",
    url: "/background-templates/bg_garden_new_1775221539240.png",
    themePreset: "garden",
    themeDetails: "lush landscaped garden, soft natural light, elegant outdoor lifestyle",
  },
  {
    id: "bg_gallery",
    category: "Environments",
    label: "Gallery",
    url: "/background-templates/bg_gallery_new_1775221560653.png",
    themePreset: "art gallery",
    themeDetails: "minimal contemporary gallery, white walls, soft even lighting",
  },
  {
    id: "bg_minimal",
    category: "Environments",
    label: "Minimal",
    url: "/background-templates/bg_minimal_new_1775221586675.png",
    themePreset: "minimal neutral interior",
    themeDetails: "light textured wall, clean lines, neutral palette",
  },
  {
    id: "bg_luxury",
    category: "Environments",
    label: "Luxury",
    url: "/background-templates/bg_luxury_new_1775221604175.png",
    themePreset: "luxury hotel / penthouse",
    themeDetails: "premium interior, tasteful decor, warm daylight",
  },
  {
    id: "bg_mediterranean_terrace",
    category: "Environments",
    label: "Mediterranean Terrace",
    url: "/background-templates/bg_mediterranean_terrace_new_1775221622857.png",
    themePreset: "mediterranean terrace",
    themeDetails: "coastal Europe resort vibe, bright sun, airy open space",
  },
  {
    id: "bg_concert",
    category: "Environments",
    label: "Concert",
    url: "/background-templates/bg_concert_new_1775221640258.png",
    themePreset: "EDM concert / music festival stage",
    themeDetails: "high-energy crowd scene, neon lasers, soft bokeh stage lighting",
  },
  {
    id: "bg_nightlife",
    category: "Environments",
    label: "Nightlife",
    url: "/background-templates/bg_nightlife_new_1775221657769.png",
    themePreset: "nightclub lounge",
    themeDetails: "upscale lounge, subtle neon accents, stylish nightlife vibe",
  }
];
